.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FREIGHT" "5" "January 2014" "" "Freight"
.
.SH "NAME"
\fBfreight\fR \- Freight configuration
.
.SH "DESCRIPTION"
The Freight configuration is a \fBsource\fRd shell script that defines a few important variables\.
.
.SH "OPTIONS"
.
.TP
\fBVARLIB\fR
The Freight library directory\. Typically \fI/var/lib/freight\fR\.
.
.TP
\fBVARCACHE\fR
The Freight cache directory\. Typically \fI/var/cache/freight\fR\. This should be the document root of the web server\.
.
.TP
\fBARCHS\fR
The architectures to support\. Typically \fIi386 amd64\fR\.
.
.TP
\fBORIGIN\fR
The \fBOrigin\fR field in the Debian archive\.
.
.TP
\fBLABEL\fR
The \fBLabel\fR field in the Debian archive\.
.
.TP
\fBCACHE\fR
\fIon\fR to cache package control files or \fIoff\fR to read them from the packages on each \fBfreight\-cache\fR(1) run\.
.
.TP
\fBGPG\fR
The GPG key to use\. This value must be set either in a configuration file or by using the \fB\-g\fR option to \fBfreight\-cache\fR(1)\.
.
.TP
\fBGPG_PASSPHRASE_FILE\fR
Pathname of a file containing the GPGP private key\'s passphrase\. This sets the \fB\-\-passphrase\-fd\fR and \fB\-\-passphrase\-file\fR options to \fBgpg\fR(1)\. The passphrase file can be set either in a configuration file or by using the \fB\-p\fR option to \fBfreight\-cache\fR(1)\.
.
.TP
\fBSYMLINKS\fR
\fIon\fR to follow symbolic links in \fBVARLIB\fR to produce extra components in the cache directory or \fIoff\fR to offer no special treatment\.
.
.SH "FILES"
.
.TP
\fI/etc/freight\.conf\fR
The default configuration file\.
.
.TP
\fI~/\.freight\.conf\fR
User\-specific configuration file\.
.
.TP
\fIetc/freight\.conf\fR, \fI\.freight\.conf\fR
Directory\-specific configuration files\.
.
.SH "ENVIRONMENT VARIABLES"
.
.TP
\fBFREIGHT_CONF\fR
The pathname of an alternate configuration file\.
.
.SH "THEME SONG"
The New Pornographers \- "All the Old Showstoppers"
.
.SH "AUTHOR"
Richard Crowley \fIr@rcrowley\.org\fR
.
.SH "SEE ALSO"
\fBfreight\-add\fR(1) adds packages to the intermediate "Freight library" that is used by \fBfreight\-cache\fR(1) to build the actual repositories\.
.
.P
\fBreprepro\fR(1) manages Debian archives, too, if Freight isn\'t your thing\.
