.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FREIGHT" "1" "January 2014" "" "Freight"
.
.SH "NAME"
\fBfreight\fR \- a modern take on the Debian archive
.
.SH "SYNOPSIS"
\fBfreight\fR \fIcommand\fR [\fI\.\.\.\fR]
.
.SH "DESCRIPTION"
\fBfreight\fR programs create the files needed to serve a Debian archive\. The actual serving is done via your favorite HTTP server\.
.
.TP
\fBfreight\-add\fR(1)
Add a package to Freight\.
.
.TP
\fBfreight\-cache\fR(1)
(Re)builds package repositories\.
.
.SH "FILES"
.
.TP
\fI/etc/freight\.conf\fR, \fI~/\.freight\.conf\fR, \fIetc/freight\.conf\fR, \fI\.freight\.conf\fR
The default configuration files\. See \fBfreight\fR(5)\.
.
.SH "ENVIRONMENT VARIABLES"
.
.TP
\fBFREIGHT_CONF\fR
The pathname of an alternate configuration file\. See \fBfreight\fR(5)\.
.
.SH "THEME SONG"
The New Pornographers \- "All the Old Showstoppers"
.
.SH "AUTHOR"
Richard Crowley \fIr@rcrowley\.org\fR
.
.SH "SEE ALSO"
\fBreprepro\fR(1) manages Debian archives, too, if Freight isn\'t your thing\.
