.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FREIGHT\-CACHE" "1" "January 2014" "" "Freight"
.
.SH "NAME"
\fBfreight\-cache\fR \- (re)builds package repositories
.
.SH "SYNOPSIS"
\fBfreight cache\fR [\fB\-k\fR] [\fB\-g\fR \fIemail\fR] [\fB\-p\fR \fIpassphrase file\fR] [\fB\-c\fR \fIconf\fR] [\fB\-v\fR] [\fB\-h\fR] [\fImanager\fR/\fIdistro\fR][\.\.\.]
.
.SH "DESCRIPTION"
\fBfreight\-cache\fR converts each \fImanager\fR/\fIdistro\fR given into a package repository (only Debian archives are supported currently)\. The \fImanager\fR indicates the type of repository (again, \fBapt\fR is the only supported value)\. The \fIdistro\fR is an arbitrary string that should match a release of the target operating system (for example, "lenny" or "lucid")\. If none are given, \fBfreight\-cache\fR converts all \fImanager\fR/\fIdistro\fR pairs found in \fB$VARLIB\fR\.
.
.P
Packages are read from the Freight library (\fB$VARLIB\fR in the configuration, see \fBfreight\fR(5)) and organized into a working repository in the Freight cache (\fB$VARCACHE\fR in the configuration)\.
.
.P
Serving the repositories is left as an exercise for the reader\. The Freight cache is the only directory that needs to be exposed, so create a virtual host with \fB$VARCACHE\fR as its document root and everything will be fine\.
.
.P
From version 0\.0\.8 onwards, distros in an APT repository no longer share the contents of the \fBpool/\fR\. After upgrading to this version and running \fBfreight\-cache\fR for all your distros, it is safe and recommended to \fBrm \-rf $VARCACHE/pool/main\fR to reset link counts to the proper value\.
.
.SH "OPTIONS"
.
.TP
\fB\-k\fR, \fB\-\-keep\fR
Keep unreferenced versions of packages\. This is different than keeping multiple versions of a package in the repository, which is supported without any special options\.
.
.TP
\fB\-g\fR \fIemail\fR, \fB\-\-gpg=\fR\fIemail\fR
Use an alternate GPG key\.
.
.TP
\fB\-p\fR \fIpassphrase file\fR, \fB\-\-passphrase\-file=\fR\fIpassphrase file\fR
Use an alternate file containing the GPG key passphrase\. This file should obviously be protected and only readable by the user running Freight\.
.
.TP
\fB\-c\fR \fIconf\fR, \fB\-\-conf=\fR\fIconf\fR
Use an alternate configuration file\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose mode\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "FILES"
.
.TP
\fI/etc/freight\.conf\fR, \fI~/\.freight\.conf\fR, \fIetc/freight\.conf\fR, \fI\.freight\.conf\fR
The default configuration files\. See \fBfreight\fR(5)\.
.
.TP
\fI$VARCACHE\fR\fB/pubkey\.gpg\fR
The exported public key used for signing each release\.
.
.SH "ENVIRONMENT VARIABLES"
.
.TP
\fBFREIGHT_CONF\fR
The pathname of an alternate configuration file\. See \fBfreight\fR(5)\.
.
.SH "THEME SONG"
The New Pornographers \- "All the Old Showstoppers"
.
.SH "AUTHOR"
Richard Crowley \fIr@rcrowley\.org\fR
.
.SH "SEE ALSO"
Part of \fBfreight\fR(1)\.
.
.P
\fBfreight\-add\fR(1) adds packages to the intermediate "Freight library" that is used by \fBfreight\-cache\fR to build the actual repositories\.
