.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FREIGHT\-ADD" "1" "January 2014" "" "Freight"
.
.SH "NAME"
\fBfreight\-add\fR \- add a package to Freight
.
.SH "SYNOPSIS"
\fBfreight add\fR [\fB\-c\fR \fIconf\fR] [\fB\-v\fR] [\fB\-h\fR] \fIpackage\fR \fImanager\fR/\fIdistro\fR[/\fIcomponent\fR][\.\.\.]
.
.SH "DESCRIPTION"
\fBfreight\-add\fR registers \fIpackage\fR with one or more \fImanager\fR/\fIdistro\fR[/\fIcomponent\fR] pairs (or triples)\. Currently, \fBapt\fR is the only supported \fImanager\fR and \fIpackage\fR must be one of \fI*\.deb\fR, \fI*\.dsc *\.debian\.tar\.gz *\.orig\.tar\.gz\fR, \fI*\.dsc *\.diff\.gz *\.orig\.tar\.gz\fR, or \fI*\.dsc *\.tar\.gz\fR\. \fIdistro\fR may be any arbitrary value but is best suited to naming a particular version of the target operating system (for example, "wheezy" or "precise")\. \fIcomponent\fR is optional and for \fBapt\fR defaults to \fBmain\fR\.
.
.P
The package files are organized in the Freight library so \fBfreight\-cache\fR(1) has an easy time of creating package repositories for each \fImanager\fR/\fIdistro\fR[/\fIcomponent\fR] later\.
.
.SH "OPTIONS"
.
.TP
\fB\-c\fR \fIconf\fR, \fB\-\-conf=\fR\fIconf\fR
Use an alternate configuration file\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose mode\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "FILES"
.
.TP
\fI/etc/freight\.conf\fR, \fI~/\.freight\.conf\fR, \fIetc/freight\.conf\fR, \fI\.freight\.conf\fR
The default configuration files\. See \fBfreight\fR(5)\.
.
.SH "ENVIRONMENT VARIABLES"
.
.TP
\fBFREIGHT_CONF\fR
The pathname of an alternate configuration file\. See \fBfreight\fR(5)\.
.
.SH "THEME SONG"
The New Pornographers \- "All the Old Showstoppers"
.
.SH "AUTHOR"
Richard Crowley \fIr@rcrowley\.org\fR
.
.SH "SEE ALSO"
Part of \fBfreight\fR(1)\.
.
.P
\fBfreight\-cache\fR(1) builds package repositories from the intermediate "Freight library" managed by \fBfreight\-add\fR\.
