.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FREIGHT\-INIT" "1" "March 2016" "" "Freight"
.
.SH "NAME"
\fBfreight\-init\fR \- initialize a Freight directory
.
.SH "SYNOPSIS"
\fBfreight init\fR [\fB\-\-libdir\fR \fIvarlib\fR] [\fB\-\-cachedir\fR \fIvarcache\fR] [\fB\-\-archs\fR \fIarchs\fR] [\fB\-\-origin\fR \fIorigin\fR] [\fB\-\-label\fR \fIlabel\fR] [\fB\-v\fR] [\fB\-h\fR] \fB\-g\fR \fIgpg\fR \fIdirname\fR
.
.SH "DESCRIPTION"
\fBfreight\-init\fR will setup a directory to be used by Freight\. It will generate small wrappers around the original Freight commands\. Use \fBfreight\-add\fR(1) and \fBfreight\-cache\fR(1) to work against the \fBVARLIB\fR and \fBVARCACHE\fR given to \fBfreight init\fR\.
.
.P
The benefit of using \fBfreight\-init\fR is to automate the setup of Freight and to configure all data to be stored in one directory\.
.
.P
Configuration is stored in \fIdirname\fR\fB/etc/freight\.conf\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-g\fR \fIgpg\fR, \fB\-\-gpg=\fR\fIgpg\fR
GPG key\. May be given multiple times\.
.
.TP
\fB\-\-libdir=\fR\fIvarlib\fR
VARLIB directory to use\. Defaults to \fIdirname\fR\fB/var/lib\fR
.
.TP
\fB\-\-cachedir=\fR\fIvarcache\fR
VARCACHE directory to use\. Defaults to \fIdirname\fR\fB/var/cache\fR
.
.TP
\fB\-\-archs=\fR\fIarchs\fR
Architectures to generate archives for\. Defaults to \fBi386 amd64\fR
.
.TP
\fB\-\-origin=\fR\fIorigin\fR
Debian archive Origin field value\. Defaults to \fBFreight\fR
.
.TP
\fB\-\-label=\fR\fIlabel\fR
Debian archive Label field value\. Defaults to \fBFreight\fR
.
.TP
\fB\-\-suite=\fR\fIsuite\fR
Debian archive Suite field value\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose mode\.
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message\.
.
.SH "FILES"
.
.TP
\fI/etc/freight\.conf\fR, \fI~/\.freight\.conf\fR, \fIetc/freight\.conf\fR, \fI\.freight\.conf\fR
The default configuration files\. See \fBfreight\fR(5)\.
.
.SH "THEME SONG"
The New Pornographers \- "All the Old Showstoppers"
.
.SH "AUTHOR"
Jens Braeuer \fIbraeuer\.jens@googlemail\.com\fR
.
.SH "SEE ALSO"
Part of \fBfreight\fR(1)\.
